export const SIGN_UP_USER = Symbol("SIGN_UP_USER");

export const START_POST_USER_SIGN_UP = Symbol("START_POST_USER_SIGN_UP");
export const POST_USER_SIGN_UP_SUCCESS = Symbol("POST_USER_SIGN_UP_SUCCESS");
export const POST_USER_SIGN_UP_FAIL = Symbol("POST_USER_SIGN_UP_FAIL");
