export const GET_PROFILE_USER = Symbol("GET_PROFILE_USER");
export const START_GET_PROFILE_USER = Symbol("START_GET_PROFILE_USER");
export const STOP_GET_PROFILE_USER = Symbol("STOP_GET_PROFILE_USER");
export const GET_PROFILE_USER_SUCCESS = Symbol("GET_PROFILE_USER_SUCCESS");
export const GET_PROFILE_USER_FAIL = Symbol("GET_PROFILE_USER_FAIL");
