export const GET_DATA_USERS = Symbol("GET_DATA_USERS");

export const START_GET_DATA = Symbol("START_GET_DATA");
export const STOP_GET_DATA = Symbol("STOP_GET_DATA");
export const GET_DATA_USERS_SUCCESS = Symbol("GET_DATA_USERS_SUCCESS");
export const GET_DATA_USERS_FAIL = Symbol("GET_DATA_USERS_FAIL");

// popularTags

export const GET_DATA_POPULAR_TAGS = Symbol("GET_DATA_POPULAR_TAGS");

export const START_GET_POPULAR_TAGS = Symbol("START_GET_POPULAR_TAGS");
export const STOP_GET_POPULAR_TAGS = Symbol("STOP_GET_POPULAR_TAGS");
export const GET_POPULAR_TAGS_SUCCESS = Symbol("GET_POPULAR_TAGS_SUCCESS");
export const GET_POPULAR_TAGS_FAIL = Symbol("GET_POPULAR_TAGS_FAIL");

// Feed

export const GET_DATA_ARTICLES = Symbol("GET_DATA_ARTICLES");

export const START_GET_DATA_ARTICLES = Symbol("START_GET_DATA_ARTICLES");
export const STOP_GET_DATA_ARTICLES = Symbol("STOP_GET_DATA_ARTICLES");
export const GET_DATA_ARTICLES_SUCCESS = Symbol("GET_DATA_ARTICLES_SUCCESS");
export const GET_DATA_ARTICLES_FAIL = Symbol("GET_DATA_ARTICLES_FAIL");
