export const POST_ARTICLE_USER = Symbol("POST_ARTICLE_USER");
//
export const POST_ARTICLE_USER_SUCCESS = Symbol("POST_ARTICLE_USER_SUCCESS");
export const POST_ARTICLE_USER_FAILURE = Symbol("POST_ARTICLE_USER_FAILURE");

///
export const GET_USER_ARTICLE = Symbol("GET_USER_ARTICLE");
//
export const GET_USER_ARTICLE_SUCCESS = Symbol("GET_USER_ARTICLE_SUCCESS");
export const GET_USER_ARTICLE_FAILURE = Symbol("GET_USER_ARTICLE_FAILURE");

/// comments
export const POST_COMMENT_USER = Symbol("POST_COMMENT_USER");
//
export const POST_COMMENT_USER_SUCCESS = Symbol("POST_COMMENT_USER_SUCCESS");
export const POST_COMMENT_USER_FAIL = Symbol("POST_COMMENT_USER_FAIL");
